stages:
  fetch_mbajk_data:
    cmd: python src/data/fetch_mbajk_data.py
    deps:
      - src/data/fetch_mbajk_data.py
    outs:
      - data/raw/mbajk/mbajk.json

  preprocess_mbajk_data:
    cmd: python src/data/preprocess_mbajk_data.py
    deps:
      - src/data/preprocess_mbajk_data.py
      - data/raw/mbajk/mbajk.json
    outs:
      - data/raw/mbajk/preprocessed_mbajk.csv

  fetch_weather_data:
    cmd: python src/data/fetch_weather_data.py
    deps:
      - src/data/fetch_weather_data.py
    outs:
      - data/raw/weather/weather.csv

  preprocess_weather_data:
    cmd: python src/data/preprocess_weather_data.py
    deps:
      - src/data/preprocess_weather_data.py
      - data/raw/weather/weather.csv
    outs:
      - data/raw/weather/preprocessed_weather.csv

  merge_processed_data:
    cmd: python src/data/merge_processed_data.py
    deps:
      - src/data/merge_processed_data.py
      - data/raw/mbajk/preprocessed_mbajk.csv
      - data/raw/weather/preprocessed_weather.csv
    outs:
      - data/processed/processed_data=DVORANA_TABOR.csv
