stages:
  fetch_mbajk_data:
    cmd: python src/data/fetch_mbajk_data.py
    deps:
      - src/data/fetch_mbajk_data.py
    outs:
      - data/raw/mbajk/mbajk.json:
          cache: false

  preprocess_mbajk_data:
    cmd: python src/data/preprocess_mbajk_data.py
    deps:
      - src/data/preprocess_mbajk_data.py
      - data/raw/mbajk/mbajk.json
      - data/raw/mbajk/all-mbajk.json
    outs:
      - data/raw/mbajk/preprocessed_mbajk.csv

  fetch_weather_data:
    cmd: python src/data/fetch_weather_data.py
    deps:
      - src/data/fetch_weather_data.py
    outs:
      - data/raw/weather/weather.csv

  preprocess_weather_data:
    cmd: python src/data/preprocess_weather_data.py
    deps:
      - src/data/preprocess_weather_data.py
      - data/raw/weather/weather.csv
      - data/raw/weather/all-weather.csv
    outs:
      - data/raw/weather/preprocessed_weather.csv

  merge_processed_data:
    cmd: python src/data/merge_processed_data.py
    deps:
      - src/data/merge_processed_data.py
      - data/raw/mbajk/preprocessed_mbajk.csv
      - data/raw/weather/preprocessed_weather.csv
    outs:
      - data/processed/processed_data=DVORANA_TABOR.csv
      - data/processed/processed_data=JHMB_–_DVOETAŽNI_MOST.csv
      - data/processed/processed_data=MLADINSKA_UL_-_TRUBARJEVA_UL.csv
      - data/processed/processed_data=PARTIZANSKA_C_-_TIC.csv
      - data/processed/processed_data=STROSSMAYERJEVA_UL_-_TRŽNICA.csv
      - data/processed/processed_data=EUROPARK_-_POBREŠKA_C.csv
      - data/processed/processed_data=KOROŠKA_C_-_KOROŠKI_VETER.csv
      - data/processed/processed_data=MLINSKA_UL__-_AVTOBUSNA_POSTAJA.csv
      - data/processed/processed_data=PARTIZANSKA_C_-_ŽELEZNIŠKA_POSTAJA.csv
      - data/processed/processed_data=TELEMACH_-_GLAVNI_TRG_-_STARI_PERON.csv
      - data/processed/processed_data=GORKEGA_UL_-_OŠ_FRANCETA_PREŠERNA.csv
      - data/processed/processed_data=LIDL_-_KOROŠKA_C.csv
      - data/processed/processed_data=NA_POLJANAH_-_HEROJA_ŠERCERJA.csv
      - data/processed/processed_data=PETROL_–_LENT_–_VODNI_STOLP.csv
      - data/processed/processed_data=ULICA_MOŠE_PIJADA_-_UKC.csv
      - data/processed/processed_data=GOSPOSVETSKA_C_-_III_GIMNAZIJA.csv
      - data/processed/processed_data=LIDL_-_TITOVA_C.csv
      - data/processed/processed_data=NICEHASH_-_C_PROLETARSKIH_BRIGAD.csv
      - data/processed/processed_data=POŠTA_-_SLOMŠKOV_TRG.csv
      - data/processed/processed_data=UM_FGPA_-_LENT_-_SODNI_STOLP.csv
      - data/processed/processed_data=GOSPOSVETSKA_C_-_TURNERJEVA_UL.csv
      - data/processed/processed_data=LJUBLJANSKA_UL_-_FOCHEVA.csv
      - data/processed/processed_data=NKBM_-_TRG_LEONA_ŠTUKLJA.csv
      - data/processed/processed_data=RAZLAGOVA_UL_-_OBČINA.csv
      - data/processed/processed_data=VZAJEMNA_VARUH_ZDRAVJA_-_BETNAVSKA_C.csv
      - data/processed/processed_data=GOSPOSVETSKA_C_-_VRBANSKA_C.csv
      - data/processed/processed_data=LJUBLJANSKA_UL_-_II_GIMNAZIJA.csv
      - data/processed/processed_data=PARTIZANSKA_C_-_CANKARJEVA_UL.csv
      - data/processed/processed_data=SPAR_-_TRŽNICA_TABOR.csv