export const stations: any[] = [
  {'id': 0, 'name': 'EUROPARK - POBREŠKA C',                  'bike_stands': 21},
  {'id': 1, 'name': 'SPAR - TRŽNICA TABOR',                   'bike_stands': 20},
  {'id': 2, 'name': 'LJUBLJANSKA UL',                         'bike_stands': 22},
  {'id': 3, 'name': 'PARTIZANSKA C',                          'bike_stands': 22},
  {'id': 4, 'name': 'JHMB – DVOETAŽNI MOST',                  'bike_stands': 22},
  {'id': 5, 'name': 'TELEMACH - GLAVNI TRG - STARI PERON',    'bike_stands': 22},
  {'id': 6, 'name': 'GOSPOSVETSKA C',                         'bike_stands': 22},
  {'id': 7, 'name': 'LIDL - KOROŠKA C',                       'bike_stands': 22},
  {'id': 8, 'name': 'POŠTA - SLOMŠKOV TRG',                   'bike_stands': 22},
  {'id': 9, 'name': 'PARTIZANSKA C',                          'bike_stands': 22},
  {'id': 10, 'name': 'PETROL – LENT – VODNI STOLP',           'bike_stands': 22},
  {'id': 11, 'name': 'None',                                  'bike_stands': 22},
  {'id': 12, 'name': 'MLINSKA UL',                            'bike_stands': 22},
  {'id': 13, 'name': 'LJUBLJANSKA UL',                        'bike_stands': 22},
  {'id': 14, 'name': 'ULICA MOŠE PIJADA - UKC',               'bike_stands': 22},
  {'id': 15, 'name': 'PARTIZANSKA C',                         'bike_stands': 22},
  {'id': 16, 'name': 'RAZLAGOVA UL',                          'bike_stands': 22},
  {'id': 17, 'name': 'KOROŠKA C',                             'bike_stands': 22},
  {'id': 18, 'name': 'NA POLJANAH - HEROJA ŠERCERJA',         'bike_stands': 22},
  {'id': 19, 'name': 'GOSPOSVETSKA C',                        'bike_stands': 22},
  {'id': 20, 'name': 'STROSSMAYERJEVA UL',                    'bike_stands': 22},
  {'id': 21, 'name': 'LIDL - TITOVA C',                       'bike_stands': 22},
  {'id': 22, 'name': 'NICEHASH - C',                          'bike_stands': 22},
  {'id': 23, 'name': 'VZAJEMNA, VARUH ZDRAVJA - BETNAVSKA C', 'bike_stands': 20},
  {'id': 24, 'name': 'UM FGPA - LENT - SODNI STOLP',          'bike_stands': 22},
  {'id': 25, 'name': 'GORKEGA UL',                            'bike_stands': 22},
  {'id': 26, 'name': 'NKBM - TRG LEONA ŠTUKLJA',              'bike_stands': 22},
  {'id': 27, 'name': 'MLADINSKA UL',                          'bike_stands': 22},
  {'id': 28, 'name': 'DVORANA TABOR',                         'bike_stands': 22},
  {'id': 29, 'name': 'GOSPOSVETSKA C',                        'bike_stands': 22}
]
