name: Deploy API to Northflank

on:
  push:
    branches:
      - main
    paths:
      - src/serve
  workflow_dispatch:

env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}

   PROJECT_ID: iis-vaja
   SERVICE_ID: iis-api
   CREDENTIALS_ID: iis-vaja-registry

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
          - name: Checkout code
            uses: actions/checkout@v4
            with:
              ref: 'main'
    
          - name: Log in to the Container registry
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
            with:
               images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          - name: Build and push Docker image
            uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
            with:
               context: .
               push: true
               tags: ${{ steps.meta.outputs.tags }}
               labels: ${{ steps.meta.outputs.labels }}
            env:
               dagshub_access_key_id: ${{ secrets.DAGSHUB_ACCSES_KEY_ID }}
               dagshub_secret_access_key_id: ${{ secrets.DAGSHUB_SECRET_ACCSES_KEY_ID }}

          - name: Deploy to Northflank
            uses: northflank/deploy-to-northflank@v1
            with:
               northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
               project-id: ${{ env.PROJECT_ID }}
               service-id: ${{ env.SERVICE_ID }}
               image-path: ${{ steps.meta.outputs.tags }}
               credentials-id: ${{ env.CREDENTIALS_ID }}
