name: Fetch MBajk data from API hourly

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version

    - name: Install dependencies
      run: |
        poetry install

    - name: Fetch data
      run: |
        poetry run python src/data/fetch_data.py

    - name: Upload fetched data
      uses: actions/upload-artifact@v2
      with:
        name: fetched-data
        path: data/raw/mbajk.json
